### ISSUE TITLE
Issue with Client Version Check

### ISSUE THREAD

**Issue by C4RP3N0CT3M** [HackShardGaming/World-of-Valheim-Public#1]
For some reason when a client connects to my server they get kicked due to a SSC version mismatch. It looks like there might just be a typo somewhere. Any help would be greatly appreciated.

Here's the error I see server-side: Peer 'steamID' has incompatible version, mine:0.150.3@0.9.7 remote 0.150.3 (WorldofValheimServerSideCharacters v0.6.1)@0.9.7

**Comment by HackShardGaming** [comment]
That error is telling you that the server does not have SSC installed.  No typo anywhere.  Make sure BepInEx is installed.
