### ISSUE TITLE
Continuing mod development

### ISSUE THREAD

**Issue by FelixReuthlinger** [HackShardGaming/World-of-Valheim-Public#5]
Hey, I just don't know even, where to talk to you about that mod. I just wanna continue development on the SSC, the other parts I am not even interested in. Since this all suddenly seemed to have you woken up - I had several things posted on you mod pages and wanted to talk to you before, but you never reacted - do you want to continue developing it? Or can I ? Prolly not, since you and a lot other now anyways mad at me...

**Comment by FelixReuthlinger** [comment]
Already deleted the mod on nexus, cannot on TS

**Comment by codewithbjim** [comment]
@FelixReuthlinger reach out to Mythic on the Thunderstore discord so you can have him remove your mod from TS
