### ISSUE TITLE
Broken in Hearth and Home

### ISSUE THREAD

**Issue by Sudo-Kid** [HackShardGaming/World-of-Valheim-Public#6]
I'm seeing the following in my console when I try and boot up with the plugins.

```
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static bool WorldofValheimServerSideCharacters.InputText_Patch::Prefix(Console instance)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <48ac0133328b486983afe98eee5b730e>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.Harmony.<PatchAll>b11_0 (System.Type type) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable1[T] sequence, System.Action1[T] action) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <48ac0133328b486983afe98eee5b730e>:0)
HarmonyLib.Harmony.PatchAll () (at <48ac0133328b486983afe98eee5b730e>:0)
WorldofValheimServerSideCharacters.WorldofValheimServerSideCharacters.Awake () (at <84ff07504db54d8da02721c839dd9374>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
```

**Comment by Gogadon** [comment]
Please fix the problem! =(
From me and my friends all characters hang on the server side!

**Comment by Sudo-Kid** [comment]
You got further then I did. It just doesn't work at all for me. Though that maybe because we are starting a new server.

**Comment by Gogadon** [comment]
Well I'm not really any further along than they probably are. I have now created a client side character file of all the players on my server with all the skill points inventory etc.
The only thing I could not do were the player stats

**Comment by wrender** [comment]
I get something similar server side, and I don't think the plugin is working as expected.  Fantastic idea for a mod though, this is a much needed feature of Valheim. :
```
Sep 18 19:16:56 supervisord: valheim-server [Info   :   Console] WoV - SSC: Loading default character file from /config/bepinex/WoV/default_character.fch
Sep 18 19:16:56 supervisord: valheim-server WoV - SSC: Loading default character file from /config/bepinex/WoV/default_character.fch
Sep 18 19:16:56 supervisord: valheim-server [Info   :   Console] WoV - SSC: Loaded default character file (Size: 240)
Sep 18 19:16:56 supervisord: valheim-server WoV - SSC: Loaded default character file (Size: 240)
Sep 18 19:16:56 supervisord: valheim-server [Info   :   Console] WoV - SSC: Backup: Creating Backup Thread!
Sep 18 19:16:56 supervisord: valheim-server WoV - SSC: Backup: Creating Backup Thread!
Sep 18 19:16:56 supervisord: valheim-server [Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type Console and name InputText and parameters 
Sep 18 19:16:56 supervisord: valheim-server ArgumentException: Undefined target method for patch method static bool WorldofValheimServerSideCharacters.InputText_Patch::Prefix(Console __instance)
Sep 18 19:16:56 supervisord: valheim-server   at HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) [0x00047] in <48ac0133328b486983afe98eee5b730e>:0 
Sep 18 19:16:56 supervisord: valheim-server   at HarmonyLib.PatchClassProcessor.Patch () [0x00059] in <48ac0133328b486983afe98eee5b730e>:0 
Sep 18 19:16:56 supervisord: valheim-server Rethrow as HarmonyException: Patching exception in method null
Sep 18 19:16:56 supervisord: valheim-server   at HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) [0x0006c] in <48ac0133328b486983afe98eee5b730e>:0 
Sep 18 19:16:56 supervisord: valheim-server   at HarmonyLib.PatchClassProcessor.Patch () [0x00084] in <48ac0133328b486983afe98eee5b730e>:0 
Sep 18 19:16:56 supervisord: valheim-server   at HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) [0x00007] in <48ac0133328b486983afe98eee5b730e>:0 
Sep 18 19:16:56 supervisord: valheim-server   at HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) [0x00014] in <48ac0133328b486983afe98eee5b730e>:0 
Sep 18 19:16:56 supervisord: valheim-server   at HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) [0x00006] in <48ac0133328b486983afe98eee5b730e>:0 
Sep 18 19:16:56 supervisord: valheim-server   at HarmonyLib.Harmony.PatchAll () [0x0001b] in <48ac0133328b486983afe98eee5b730e>:0 
Sep 18 19:16:56 supervisord: valheim-server   at WorldofValheimServerSideCharacters.WorldofValheimServerSideCharacters.Awake () [0x001e8] in <554d08fa81044ee99f519c71e3007a65>:0 
Sep 18 19:16:56 supervisord: valheim-server UnityEngine.GameObject:Internal_AddComponentWithType(Type)
Sep 18 19:16:56 supervisord: valheim-server UnityEngine.GameObject:AddComponent(Type)
Sep 18 19:16:56 supervisord: valheim-server BepInEx.Bootstrap.Chainloader:Start()
Sep 18 19:16:56 supervisord: valheim-server UnityEngine.Application:.cctor()
```

**Comment by Gogadon** [comment]
It is probably because the mod no longer works through the H&H update?

**Comment by wrender** [comment]
I'm not sure. Most likely I guess. Hopefully @HackShardGaming  is able to help us out!

**Comment by IrcDirk** [comment]
Yeap... Confirming it doesnt work with the newest update H&H. Hopefully someone will find time to update this great mod.

**Comment by HackShardGaming** [comment]
Sorry that I haven't been around guys.  I quit making modifications to this mod a long while ago as I just did not have the time.  However, I have said and posted in the permissions on the site that if someone wants to continue the work they can but they have to give credit to the original mod developer and myself.  Thanks guys! I hope someone continues this great mod!

**Comment by wrender** [comment]
Well shucks @HackShardGaming . :) What if we paid you for your time?  I would offer to help, but really don't know much about unity or c# or whatever it uses.

**Comment by HackShardGaming** [comment]
I still wouldn't work on it to be honest with you.  I haven't played the game in over 4 months.  I have way to much on my plate right now.  Sorry guys!

**Comment by HackShardGaming** [comment]
Ok so one of my friends took a look at the code.  He says the only thing he can see that's wrong is how we tie into console chat.  It is now called Terminal chat or something.  I'll see if he can't post a fix for yall.

**Comment by wrender** [comment]
That would be amazing @HackShardGaming .  If you want include me on the pull request and I test on a few servers and clients.

**Comment by Brohl1337** [comment]
Gosh i love you @HackShardGaming <3

**Comment by klugemonkey** [comment]
Can check my fork for an update.  If commits are fine, please include.

**Comment by Brohl1337** [comment]
> 
> 
> Can check my fork for an update. If commits are fine, please include.

Works like a charm! Ty mate!

**Comment by wrender** [comment]
Stupid question. But how do you build this?

**Comment by wrender** [comment]
Thank you so much!

**Comment by HackShardGaming** [comment]
@klugemonkey as long as you are fine with me releasing it sent a merge request and I'll pull it and put it out there. Thanks bro!

**Comment by HackShardGaming** [comment]
Thank you @klugemonkey for the patches.  I have updated all the nexusmods pages and this one.  I included credit to you in my version updates on Nexusmods as well.  Appreciate your help! Now everyone keep enjoying what my mod brings you :P

**Comment by SenjayY** [comment]
[Info   :   Console] WoV - SSC: Version Generated: 0.202.19 (WorldofValheimServerSideCharacters v0.7.2)
[Info   : Unity Log] 09/25/2021 21:30:26: VERSION check their:0.202.19 (WorldofValheimServerSideCharacters v0.7.2)  mine:0.202.19 (WorldofValheimServerSideCharacters v0.7.2)

[Info   :   Console] WoV - SSC: Version Generated: 0.202.19 (WorldofValheimServerSideCharacters v0.7.2)
[Info   :   Console] WoV - SSC: Version Generated: 0.202.19 (WorldofValheimServerSideCharacters v0.7.2)
[Info   :   Console] WoV - SSC: Server->Client CharacterData
[Info   : Unity Log] 09/25/2021 21:30:26: Exception in ZRpc::HandlePackage: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at WorldofValheimServerSideCharacters.Util.LoadOrMakeCharacter (System.String steamid) [0x00017] in <9d5c757def204f07b82d1c6fb6fd1acd>:0 
  at WorldofValheimServerSideCharacters.StandalonePatches.ZNet__SendPeerInfo (ZNet __instance, ZRpc rpc) [0x0002c] in <9d5c757def204f07b82d1c6fb6fd1acd>:0 
  at (wrapper dynamic-method) ZNet.DMD<ZNet::SendPeerInfo>(ZNet,ZRpc,string)
  at ZNet.RPC_PeerInfo (ZRpc rpc, ZPackage pkg) [0x003e2] in <e722c8a71dc84a138485f8895f96ae76>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <eae584ce26bc40229c1b1aa476bfa589>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x000e7] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00008] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at ZRpc+RpcMethod`1[T].Invoke (ZRpc rpc, ZPackage pkg) [0x0001d] in <e722c8a71dc84a138485f8895f96ae76>:0 
  at ZRpc.HandlePackage (ZPackage package) [0x00049] in <e722c8a71dc84a138485f8895f96ae76>:0 
  at ZRpc.Update (System.Single dt) [0x0003e] in <e722c8a71dc84a138485f8895f96ae76>:0 
  
  I have this problem,my friend is joining and he appears in the lobbyinfo (f2) but he has infinite loading screen,when i check on logoutput.log i notice those error ^^
