### ISSUE TITLE
Feature Request - output map pin name/coords to text file

### ISSUE THREAD

**Issue by maxfield-allison** [HackShardGaming/World-of-Valheim-Public#7]
@HackShardGaming I understand you aren't really putting time into this mod anymore but I'm trying to add a couple hundred smaller zones and I'd love to not have to go manually to each location in order to create them. @klugemonkey, would this be somehting you could assist with?

**Comment by HackShardGaming** [comment]
You don't have to manually insert the coordinates.  As long as you know the center of each zone (the X and Y) and the radius you want to use etc. You can just manually add it to your zones file. then you can !reloadzones or however I have the command typed in the help list cause I can't remember lol.  Just give it a shot!
